export enum EEstadoPedido {
    ENTREGADO = "ENTREGADO",
    CAMINO = "CAMINO",
    PENDIENTE = "PENDIENTE",
    ESPERA = "ESPERA",
    PREPARACION = "PREPARACION",
    PREPARADO = "PREPARADO",
    RECHAZADO = "RECHAZADO"
  }
  